[package]
name = "lecture_03-10_10"
version = "0.1.0"
edition = "2021"

[profile.release]
overflow-checks = true
#panic = "unwind" (default) | "abort" (no unwinding)

[profile.dev]

[dependencies]
slug = "0.1.4"